centers/urls.py
from .views import CenterListDetailUpdateDeleteAPIView,CenterReviewDetailUpdateDeleteAPIView,CenterList,CenterDetailView
from django.urls import path

app_name = 'centers'


urlpatterns = [
    path('api', CenterListDetailUpdateDeleteAPIView.as_view()),
    path('api/<int:pk>/', CenterReviewDetailUpdateDeleteAPIView.as_view()),

    path('',CenterList.as_view(), name='center-list'),
    path('<int:pk>/center-detail/', CenterDetailView.as_view(), name='center-detail'),

]

src/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from src import settings

schema_view = get_schema_view(
   openapi.Info(
      title="Learning Center apis",
      default_version='v1.2',
      description="Learning centers information",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="nencymmmm@gmail.com"),
      license=openapi.License(name="No"),
   ),
   public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('users/', include('users.urls')),
    path('centers/', include('centers.urls')),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration', include('dj_rest_auth.registration.urls')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from .views import CustomUserListUpdateDelateAPIView, CustomUserDetailUpdateDelateAPIView, UserRegisterView, \
    CustomUserLogin, LogoutView, ProfileView, ProfileUpdateView
from django.urls import path

app_name = 'users'
urlpatterns = [
    path("user-list/", CustomUserListUpdateDelateAPIView.as_view()),
    path("user-list/<int:pk>", CustomUserDetailUpdateDelateAPIView.as_view()),

    path('register/', UserRegisterView.as_view(), name='regis'),
    path('login/', CustomUserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
]

templates/base.html
{% load static %}


<html lang="en">
<head>
<meta charset="UTF-8">


    <title>{% block title %} Learning Centers  {% endblock title %}</title>
<!--    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">-->
<!--    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">-->

<style>
        img{
        width:200px;
        height:200px;
        }
</style>
</head>
<body>
<h1>Learning Centers</h1>
<a href="{% url 'home' %}">Home Page</a>


{% block content %}



{% endblock content %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home  {% endblock title %}

{% block content %}
<h2>Landing page</h2>
{% if user.is_authenticated %}
    <p><a href="{% url 'centers:center-list' %}">Centers</a></p>
    <p><a href="{% url 'users:logout' %}">Logout</a></p>
    <p><a href="{% url 'users:regis' %}">Register</a></p>
    <p><a href="{% url 'users:profile' %}">Profile</a></p>

{% else %}
    <p><a href="{% url 'centers:center-list' %}">Centers</a></p>
    <p><a href="{% url 'users:login' %}">Login</a></p>
    <p><a href="{% url 'users:regis' %}">Register</a></p>
{% endif %}

{% endblock content %}